// hng13/frontend/hng13-stage2/ticketapp-vue/src/components/ToastProvider.vue
<template>
  <div>
    <slot />
    <div
      aria-live="polite"
      class="fixed right-4 bottom-4 z-50 flex flex-col gap-2"
    >
      <div
        v-for="t in toasts"
        :key="t.id"
        :class="['p-3 rounded shadow-lg max-w-xs', toastClass(t.type)]"
      >
        {{ t.message }}
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { toastStore } from "../composables/useToast"; // Adjust path as needed

export default defineComponent({
  setup() {
    return {
      toasts: toastStore.toasts,
      toastClass(type: "success" | "error" | "info") {
        return type === "success"
          ? "bg-green-600 text-white"
          : type === "error"
          ? "bg-red-600 text-white"
          : "bg-blue-600 text-white";
      },
    };
  },
});
</script>

// hng13/frontend/hng13-stage2/ticket-app-react/src/componenets/ToastProvider.tsx
import { createContext, useContext, useState } from "react";

type Toast = {
  id: string;
  type: "success" | "error" | "info";
  message: string;
};

const ToastCtx = createContext({
  push: (_t: Omit<Toast, "id">) => {},
});

export const useToast = () => useContext(ToastCtx);

export const ToastProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [toasts, setToasts] = useState<Toast[]>([]);

  const push = (t: Omit<Toast, "id">) => {
    const id = Math.random().toString(36).slice(2);
    setToasts((s) => [...s, { id, ...t }]);
    setTimeout(() => {
      setToasts((s) => s.filter((x) => x.id !== id));
    }, 4000);
  };

  return (
    <ToastCtx.Provider value={{ push }}>
      {children}
      <div
        aria-live="polite"
        className="fixed right-4 bottom-4 z-50 flex flex-col gap-2"
      >
        {toasts.map((t) => (
          <div
            key={t.id}
            className={`p-3 rounded shadow-lg max-w-xs ${
              t.type === "success"
                ? "bg-green-600 text-white"
                : t.type === "error"
                ? "bg-red-600 text-white"
                : "bg-blue-600 text-white"
            }`}
          >
            {t.message}
          </div>
        ))}
      </div>
    </ToastCtx.Provider>
  );
};
