// hng13/frontend/hng13-stage2/ticket-app-react/src/pages/Login.tsx
import { Link, useNavigate } from "react-router-dom";
import { useToast } from "../componenets/ToastProvider";
import { useState } from "react";
import { createSession } from "../services/session";
import Header from "../componenets/Header";

interface errorType {
  username?: string;
  password?: string;
}

const Login = () => {
  const nav = useNavigate();
  const toast = useToast();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [errors, setErrors] = useState<errorType>({});

  function submit(e: React.FormEvent) {
    e.preventDefault();

    const errs: any = {};
    if (!username) errs.username = "Username required";
    if (!password) errs.password = "Password required";
    setErrors(errs);
    if (Object.keys(errs).length) return;

    if (username.trim() && password.length >= 4) {
      createSession(username.trim());
      toast.push({ type: "success", message: "Signed in successfully" });
      nav("/dashboard");
    } else {
      toast.push({ type: "error", message: "Invalid credentials " });
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <div className="max-w-[1440px] mx-auto px-4 py-6">
        <h2 className="text-2xl font-semibold mb-4">Login</h2>
        <form onSubmit={submit} className="max-w-md">
          <label className="block mb-2">
            Username
            <input
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="input"
            />
            {errors.username && (
              <div className="text-sm text-red-600">{errors.username}</div>
            )}
          </label>
          <label className="block mb-2">
            Password
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="input"
            />
            {errors.password && (
              <div className="text-sm text-red-600">{errors.password}</div>
            )}
          </label>
          <div className="flex gap-3 mt-3">
            <button className="btn" type="submit">
              Login
            </button>
            <Link to="/auth/signup" className="btn-outline">
              Create account
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;

// hng13/frontend/hng13-stage2/ticketapp-vue/src/views/Login.vue
<template>
  <div class="min-h-screen flex flex-col">
    <AppHeader />
    <div class="max-w-[1440px] mx-auto px-4 py-6">
      <h2 class="text-2xl font-semibold mb-4">Login</h2>
      <form @submit.prevent="submit" class="max-w-md">
        <label class="block mb-2"
          >Username
          <input v-model="username" class="input" />
          <div v-if="errors.username" class="text-sm text-red-600">
            {{ errors.username }}
          </div>
        </label>
        <label class="block mb-2"
          >Password
          <input type="password" v-model="password" class="input" />
          <div v-if="errors.password" class="text-sm text-red-600">
            {{ errors.password }}
          </div>
        </label>
        <div class="flex gap-3 mt-3">
          <button class="btn" type="submit">Login</button>
          <router-link to="/auth/signup" class="btn-outline"
            >Create account</router-link
          >
        </div>
      </form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive } from "vue";
import AppHeader from "../components/AppHeader.vue";
import { createSession } from "../services/session";
import { useToast } from "../composables/useToast";
import { useRouter } from "vue-router";
import { toRefs } from "vue";

export default defineComponent({
  components: { AppHeader },
  setup() {
    const state = reactive({
      username: "",
      password: "",
      errors: {} as Record<string, string>,
    });
    const router = useRouter();
    const toast = useToast();

    function submit() {
      state.errors = {};
      if (!state.username) state.errors.username = "Username required";
      if (!state.password) state.errors.password = "Password required";
      if (Object.keys(state.errors).length) return;
      if (state.username.trim() && state.password.length >= 4) {
        createSession(state.username.trim());
        toast.push({ type: "success", message: "Signed in successfully" });
        router.push("/dashboard");
      } else {
        toast.push({ type: "error", message: "Invalid credentials" });
      }
    }

    return { ...toRefs(state), submit };
  },
});
</script>
